on:
  release:
    types:
      - published

name: release

permissions:
  # Needed to access the workflow's OIDC identity.
  id-token: write

  # Needed to upload release assets.
  contents: write

jobs:
  pypi:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ">= 3.7"

    - name: deps
      run: python -m pip install -U setuptools build wheel

    - name: build
      run: python -m build

    - name: publish
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}

    - name: sign
      uses: sigstore/gh-action-sigstore-python@v0.0.9
      with:
        inputs: ./dist/*.tar.gz ./dist/*.whl

    - name: upload artifacts to github
      # Confusingly, this action also supports updating releases, not
      # just creating them. This is what we want here, since we've manually
      # created the release that triggered the action.
      uses: softprops/action-gh-release@v1
      with:
        # dist/ contains the built packages, which smoketest-artifacts/
        # contains the signatures and certificates.
        files: dist/*
