name: Test
on: [push, pull_request]
concurrency:
  group: >-
    ${{
        github.workflow
    }}-${{
        github.ref_type
    }}-${{
        github.event.pull_request.number || github.sha
    }}
  cancel-in-progress: true
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
      - name: Install tox
        run: python -m pip install tox
      - name: Run linting
        run: python -m tox -e lint

  build-matrix:
    name: Build the test matrix
    needs: lint
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
      - name: Install tox
        run: python -m pip install tox
      - id: set-matrix
        run: >-
          echo "matrix=$(python generate_matrix.py)" >> "${GITHUB_OUTPUT}"

  test:
    name: ${{ matrix.toxenv }}
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: python -m pip install tox
      - name: Run tests
        run: python -m tox -e ${{ matrix.toxenv }}

  check:
    if: always()
    needs:
    - test
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
